# Generated by Django 6.1 on 2026-08-22 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_alter_person_options_alter_profileownership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW_PRIVATE_RESOURCE', 'Просмотр закрытых данных'), ('VIEW_MEDIA', 'Просмотр файла'), ('APPROVE_MEDIA', 'Одобрение файла'), ('REJECT_MEDIA', 'Отклонение файла'), ('VERIFY_HERITAGE', 'Проверка исторических данных'), ('GRANT_ACCESS', 'Выдача доступа'), ('REVOKE_ACCESS', 'Отзыв доступа'), ('APPROVE_CHANGE', 'Одобрение изменения'), ('REJECT_CHANGE', 'Отклонение изменения')], max_length=50, verbose_name='Действие')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='family.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'), models.Index(fields=['person', 'created_at'], name='audit_audit_person__35f379_idx')],
            },
        ),
    ]
