# Generated by Django 6.1 on 2026-09-05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Контекст",
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    (
                        "VIEW_PRIVATE_RESOURCE",
                        "Просмотр закрытых данных",
                    ),
                    ("VIEW_MEDIA", "Просмотр файла"),
                    ("APPROVE_MEDIA", "Одобрение файла"),
                    ("REJECT_MEDIA", "Отклонение файла"),
                    (
                        "VERIFY_HERITAGE",
                        "Проверка исторических данных",
                    ),
                    (
                        "UPDATE_PRIVACY_POLICY",
                        "Изменение приватности",
                    ),
                    ("REQUEST_ACCESS", "Запрос доступа"),
                    (
                        "REJECT_ACCESS",
                        "Отклонение запроса доступа",
                    ),
                    ("GRANT_ACCESS", "Выдача доступа"),
                    ("REVOKE_ACCESS", "Отзыв доступа"),
                    ("APPROVE_CHANGE", "Одобрение изменения"),
                    ("REJECT_CHANGE", "Отклонение изменения"),
                ],
                max_length=50,
                verbose_name="Действие",
            ),
        ),
    ]
