# Generated by Django 6.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit",
            "0003_alter_auditevent_action_invitation_actions",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    (
                        "VIEW_PRIVATE_RESOURCE",
                        "Просмотр закрытых данных",
                    ),
                    ("VIEW_MEDIA", "Просмотр файла"),
                    ("APPROVE_MEDIA", "Одобрение файла"),
                    ("REJECT_MEDIA", "Отклонение файла"),
                    (
                        "VERIFY_HERITAGE",
                        "Проверка исторических данных",
                    ),
                    (
                        "UPDATE_PRIVACY_POLICY",
                        "Изменение приватности",
                    ),
                    ("REQUEST_ACCESS", "Запрос доступа"),
                    (
                        "REJECT_ACCESS",
                        "Отклонение запроса доступа",
                    ),
                    (
                        "CREATE_INVITATION",
                        "Создание приглашения",
                    ),
                    (
                        "ACCEPT_INVITATION",
                        "Принятие приглашения",
                    ),
                    (
                        "CANCEL_INVITATION",
                        "Отмена приглашения",
                    ),
                    (
                        "REQUEST_CHANGE",
                        "Создание заявки на изменение",
                    ),
                    ("GRANT_ACCESS", "Выдача доступа"),
                    ("REVOKE_ACCESS", "Отзыв доступа"),
                    ("APPROVE_CHANGE", "Одобрение изменения"),
                    ("REJECT_CHANGE", "Отклонение изменения"),
                ],
                max_length=50,
                verbose_name="Действие",
            ),
        ),
    ]
