# Generated by Django 6.1 on 2026-09-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE_PERSON', 'Создание человека'), ('UPDATE_RELATIONSHIP', 'Изменение родственной связи'), ('DELETE_RELATIONSHIP', 'Удаление родственной связи'), ('CREATE_RELATIONSHIP', 'Создание родственной связи'), ('VIEW_PRIVATE_RESOURCE', 'Просмотр закрытых данных'), ('UPLOAD_MEDIA', 'Загрузка файла'), ('VIEW_MEDIA', 'Просмотр файла'), ('APPROVE_MEDIA', 'Одобрение файла'), ('REJECT_MEDIA', 'Отклонение файла'), ('ARCHIVE_MEDIA', 'Архивирование файла'), ('VERIFY_HERITAGE', 'Проверка исторических данных'), ('CREATE_SOURCE', 'Создание источника'), ('ATTACH_SOURCE', 'Привязка источника'), ('UPDATE_SOURCE_LINK', 'Изменение связи с источником'), ('DETACH_SOURCE', 'Отвязка источника'), ('UPDATE_PRIVACY_POLICY', 'Изменение приватности'), ('REQUEST_ACCESS', 'Запрос доступа'), ('REJECT_ACCESS', 'Отклонение запроса доступа'), ('CREATE_INVITATION', 'Создание приглашения'), ('ACCEPT_INVITATION', 'Принятие приглашения'), ('CANCEL_INVITATION', 'Отмена приглашения'), ('REQUEST_CHANGE', 'Создание заявки на изменение'), ('GRANT_ACCESS', 'Выдача доступа'), ('REVOKE_ACCESS', 'Отзыв доступа'), ('APPROVE_CHANGE', 'Одобрение изменения'), ('REJECT_CHANGE', 'Отклонение изменения')], max_length=50, verbose_name='Действие'),
        ),
    ]
