# Generated by Django 6.1 on 2026-08-18 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('family', '0002_alter_person_options_alter_profileownership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Приглашён'), ('ACTIVE', 'Активен'), ('SUSPENDED', 'Приостановлен'), ('DISABLED', 'Отключён')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('FAMILY_MEMBER', 'Член семьи'), ('FAMILY_HISTORIAN', 'Семейный историк'), ('SYSTEM_ADMIN', 'Системный администратор')], default='FAMILY_MEMBER', max_length=30),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принято'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='family.person', verbose_name='Человек')),
            ],
        ),
    ]
