# Generated by Django 6.1 on 2026-08-18 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('EMPLOYMENT', 'Место работы'), ('EDUCATION', 'Образование'), ('SKILL', 'Навык')], max_length=30, verbose_name='Тип данных')),
                ('object_id', models.UUIDField(verbose_name='ID записи')),
                ('action', models.CharField(choices=[('EDIT', 'Редактирование'), ('DELETE', 'Удаление')], max_length=20, verbose_name='Действие')),
                ('proposed_data', models.JSONField(blank=True, default=dict, verbose_name='Предлагаемые данные')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает рассмотрения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор запроса')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_profile_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
            ],
            options={
                'verbose_name': 'Запрос на изменение',
                'verbose_name_plural': 'Запросы на изменения',
                'ordering': ['-requested_at'],
            },
        ),
    ]
