# Generated by Django 6.1 on 2026-08-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilechangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Добавление'), ('EDIT', 'Редактирование'), ('DELETE', 'Удаление')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='object_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID записи'),
        ),
    ]
