# Generated by Django 6.1 on 2026-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profilechangerequest_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='resource_type',
            field=models.CharField(choices=[('EMPLOYMENT', 'Место работы'), ('EDUCATION', 'Образование'), ('SKILL', 'Навык'), ('HELP_OFFER', 'Предложение помощи'), ('BIOGRAPHY', 'Биография'), ('LIFE_EVENT', 'Событие жизни')], max_length=30, verbose_name='Тип данных'),
        ),
    ]
