# Generated by Django 6.1 on 2026-09-05 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profilechangerequest_resource_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profilechangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('object_id__isnull', False), ('status', 'PENDING')), fields=('resource_type', 'object_id'), name='unique_pending_change_request_per_resource'),
        ),
    ]
