# Generated by Django 6.1 on 2026-08-16 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_precision', models.CharField(choices=[('EXACT', 'Exact'), ('MONTH_ONLY', 'Month only'), ('YEAR_ONLY', 'Year only'), ('APPROXIMATE', 'Approximate'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('profile_status', models.CharField(choices=[('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed'), ('HERITAGE', 'Heritage'), ('ARCHIVED', 'Archived')], default='UNCLAIMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='family.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('person',), name='one_confirmed_owner_per_person'), models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('user',), name='one_confirmed_person_per_user')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('PARENT_CHILD', 'Parent → Child'), ('SPOUSE', 'Spouse'), ('PARTNER', 'Partner'), ('SIBLING', 'Sibling'), ('ADOPTIVE_PARENT', 'Adoptive Parent → Child'), ('GUARDIAN', 'Guardian → Person')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='family.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='family.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('person_a', models.F('person_b')), _negated=True), name='relationship_not_self')],
            },
        ),
    ]
