# Generated by Django 6.1 on 2026-08-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='profileownership',
            options={'verbose_name': 'Владелец профиля', 'verbose_name_plural': 'Владельцы профилей'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Родственная связь', 'verbose_name_plural': 'Родственные связи'},
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date_precision',
            field=models.CharField(choices=[('EXACT', 'Точная дата'), ('MONTH_ONLY', 'Известны месяц и год'), ('YEAR_ONLY', 'Известен только год'), ('APPROXIMATE', 'Приблизительно'), ('UNKNOWN', 'Неизвестно')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_status',
            field=models.CharField(choices=[('UNCLAIMED', 'Не подтверждён владельцем'), ('CLAIMED', 'Подтверждён владельцем'), ('HERITAGE', 'Исторический профиль'), ('ARCHIVED', 'Архив')], default='UNCLAIMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('PARENT_CHILD', 'Родитель → ребёнок'), ('SPOUSE', 'Супруг / супруга'), ('PARTNER', 'Партнёр'), ('SIBLING', 'Брат / сестра'), ('ADOPTIVE_PARENT', 'Приёмный родитель → ребёнок'), ('GUARDIAN', 'Опекун → человек')], max_length=30),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает проверки'), ('VERIFIED', 'Подтверждено'), ('DISPUTED', 'Есть разногласия')], default='PENDING', max_length=20),
        ),
    ]
