# Generated by Django 6.1 on 2026-08-18 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_alter_person_options_alter_profileownership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Биография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_biographies', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='family.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Биография',
                'verbose_name_plural': 'Биографии',
            },
        ),
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MOVE', 'Переезд'), ('EDUCATION', 'Образование'), ('EMPLOYMENT', 'Работа'), ('MARRIAGE', 'Брак'), ('AWARD', 'Награда'), ('MILITARY_SERVICE', 'Военная служба'), ('TRAVEL', 'Путешествие'), ('FAMILY', 'Семейное событие'), ('OTHER', 'Другое')], default='OTHER', max_length=30, verbose_name='Тип события')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('date_precision', models.CharField(choices=[('EXACT', 'Точная дата'), ('MONTH', 'Известен месяц'), ('YEAR', 'Известен только год'), ('APPROXIMATE', 'Примерная дата'), ('UNKNOWN', 'Дата неизвестна')], default='EXACT', max_length=20, verbose_name='Точность даты')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='Место')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_life_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='family.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Событие жизни',
                'verbose_name_plural': 'События жизни',
                'ordering': ['start_date', 'created_at'],
            },
        ),
    ]
