# Generated by Django 6.1 on 2026-08-18 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('ORAL', 'Устный рассказ'), ('DOCUMENT', 'Документ'), ('PHOTO', 'Фотография'), ('ARCHIVE', 'Архивная запись'), ('BOOK', 'Книга / публикация'), ('WEBSITE', 'Веб-сайт'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип источника')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор / рассказчик')),
                ('source_date', models.DateField(blank=True, null=True, verbose_name='Дата источника')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('citation', models.TextField(blank=True, verbose_name='Описание / ссылка на источник')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['-source_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('BIOGRAPHY', 'Биография'), ('LIFE_EVENT', 'Событие жизни')], max_length=30, verbose_name='Тип объекта')),
                ('object_id', models.UUIDField(verbose_name='ID объекта')),
                ('relation_type', models.CharField(choices=[('SUPPORTS', 'Подтверждает'), ('CONTRADICTS', 'Противоречит'), ('CONTEXT', 'Дополнительный контекст')], default='SUPPORTS', max_length=20, verbose_name='Роль источника')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий к связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_source_links', to=settings.AUTH_USER_MODEL, verbose_name='Добавил связь')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='heritage.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Связь с источником',
                'verbose_name_plural': 'Связи с источниками',
                'constraints': [models.UniqueConstraint(fields=('source', 'resource_type', 'object_id'), name='unique_source_resource_link')],
            },
        ),
    ]
