# Generated by Django 6.1 on 2026-08-19 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_source_sourcelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('BIOGRAPHY', 'Биография'), ('LIFE_EVENT', 'Событие жизни')], max_length=30, verbose_name='Тип объекта')),
                ('object_id', models.UUIDField(verbose_name='ID объекта')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'Ожидает проверки'), ('VERIFIED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('DISPUTED', 'Спорное'), ('ARCHIVED', 'Архивировано')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heritage_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Проверка достоверности',
                'verbose_name_plural': 'Проверки достоверности',
                'constraints': [models.UniqueConstraint(fields=('resource_type', 'object_id'), name='unique_heritage_verification')],
            },
        ),
    ]
