# Generated by Django 6.1 on 2026-08-22 12:44

import django.core.files.storage
import django.db.models.deletion
import heritage.models
import pathlib
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_person_options_alter_profileownership_options_and_more'),
        ('heritage', '0003_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('PHOTO', 'Фотография'), ('DOCUMENT', 'Документ')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/app/private_media')), upload_to=heritage.models.private_media_upload_path, verbose_name='Файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает проверки'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('ARCHIVED', 'Архивировано')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='family.person', verbose_name='Человек')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_family_media', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_family_media', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Семейный файл',
                'verbose_name_plural': 'Семейные файлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
