# Generated by Django 6.1 on 2026-08-22 13:06

import django.core.files.storage
import heritage.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0004_mediaasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/app/private_media')), upload_to=heritage.models.private_media_upload_path, verbose_name='Файл'),
        ),
    ]
