# Generated by Django 6.1 on 2026-09-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_alter_mediaasset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('ARCHIVED', 'Архивирован')], default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
    ]
