# Generated by Django 6.1 on 2026-08-18 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_alter_person_options_alter_profileownership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('EMPLOYMENT', 'Место работы'), ('EDUCATION', 'Образование'), ('SKILL', 'Навык'), ('HELP_OFFER', 'Предложение помощи')], max_length=30, verbose_name='Тип данных')),
                ('object_id', models.UUIDField(verbose_name='ID записи')),
                ('visibility', models.CharField(choices=[('FAMILY', 'Вся семья'), ('SELECTED_USERS', 'Выбранные пользователи'), ('REQUEST_ONLY', 'Только по запросу'), ('OWNER_ONLY', 'Только владелец'), ('PRIVATE', 'Скрыто')], default='FAMILY', max_length=30, verbose_name='Видимость')),
                ('show_existence', models.BooleanField(default=True, verbose_name='Показывать существование скрытых данных')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policies', to='family.person', verbose_name='Владелец данных')),
            ],
            options={
                'verbose_name': 'Политика приватности',
                'verbose_name_plural': 'Политики приватности',
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, verbose_name='Причина запроса')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает рассмотрения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='privacy.privacypolicy', verbose_name='Политика')),
            ],
            options={
                'verbose_name': 'Запрос доступа',
                'verbose_name_plural': 'Запросы доступа',
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW', 'Просмотр')], default='VIEW', max_length=20, verbose_name='Действие')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_grants', to=settings.AUTH_USER_MODEL, verbose_name='Кому разрешено')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='privacy.privacypolicy', verbose_name='Политика')),
            ],
            options={
                'verbose_name': 'Разрешение доступа',
                'verbose_name_plural': 'Разрешения доступа',
            },
        ),
        migrations.AddConstraint(
            model_name='privacypolicy',
            constraint=models.UniqueConstraint(fields=('resource_type', 'object_id'), name='unique_privacy_policy_per_resource'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('policy', 'requester'), name='unique_pending_access_request'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('policy', 'grantee', 'action'), name='unique_active_access_grant'),
        ),
    ]
