# Generated by Django 6.1 on 2026-08-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_alter_privacypolicy_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='resource_type',
            field=models.CharField(choices=[('EMPLOYMENT', 'Место работы'), ('EDUCATION', 'Образование'), ('SKILL', 'Навык'), ('HELP_OFFER', 'Предложение помощи'), ('BIOGRAPHY', 'Биография'), ('LIFE_EVENT', 'Событие жизни'), ('MEDIA_ASSET', 'Фото / документ')], max_length=30, verbose_name='Тип данных'),
        ),
    ]
