# Generated by Django 6.1 on 2026-08-18 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0002_alter_person_options_alter_profileownership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Чем могу помочь')),
                ('category', models.CharField(choices=[('PROFESSIONAL', 'Профессиональная помощь'), ('EDUCATION', 'Обучение'), ('ADVICE', 'Совет / консультация'), ('PRACTICAL', 'Практическая помощь'), ('OTHER', 'Другое')], default='OTHER', max_length=30, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_offers', to='family.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Предложение помощи',
                'verbose_name_plural': 'Предложения помощи',
                'ordering': ['title'],
            },
        ),
    ]
